[package]
name = "web-server-atack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "HTTPClient"
path = "src/HTTPClient.rs"
 
[dependencies]
curl = "0.4.43"
